<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${pageTitle} | Travelgram</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
<c:url var="globalCss" value="/assets/css/global.css"/><c:url var="themeCss" value="/assets/css/theme.css"/><c:url var="layoutCss" value="/assets/css/layout.css"/><c:url var="componentsCss" value="/assets/css/components.css"/><c:url var="pagesCss" value="/assets/css/pages.css"/><c:url var="appJs" value="/assets/js/app.js"/>
<link rel="stylesheet" href="${globalCss}"><link rel="stylesheet" href="${themeCss}"><link rel="stylesheet" href="${layoutCss}"><link rel="stylesheet" href="${componentsCss}"><link rel="stylesheet" href="${pagesCss}"></head><body><div class="tg-app">
<jsp:include page="fragments/header.jsp"/><div class="tg-layout"><jsp:include page="fragments/sidebar.jsp"><jsp:param name="active" value="${pageKey}"/></jsp:include><main class="tg-content">
<section class="tg-panel tg-page-header"><h1>${pageTitle}</h1><p>여행의 순간과 정보를 함께 나누세요.</p></section>
<c:choose>
  <c:when test="${pageKey eq 'travelgram'}"><section class="tg-panel tg-page-body"><div class="tg-travel-grid"><c:forEach var="city" items="${['seoul','busan','jeju','gangneung','gyeongju','sokcho','incheon','jeonju','seoul']}"><c:url var="img" value="/assets/images/${city}.svg"/><a href="<c:url value='/post-detail'/>"><img src="${img}" alt="${city}"></a></c:forEach></div></section></c:when>
  <c:when test="${pageKey eq 'chat'}"><section class="tg-panel tg-chat-shell"><div class="tg-chat-list"><div class="tg-chat-row"><img class="tg-avatar" src="<c:url value='/assets/images/profile-sora.svg'/>" alt="sora"><div class="tg-chat-bubble"><strong>travel_sora</strong><br>제주 동쪽 코스 추천해 드릴까요?</div></div><div class="tg-chat-row"><img class="tg-avatar" src="<c:url value='/assets/images/profile-min.svg'/>" alt="min"><div class="tg-chat-bubble"><strong>budget_min</strong><br>가성비 숙소 리스트를 공유했어요.</div></div></div><form class="tg-compose" data-demo-form><input class="form-control" placeholder="메시지를 입력하세요"><button class="btn btn-primary">전송</button></form></section></c:when>
  <c:when test="${pageKey eq 'tag'}"><section class="tg-panel tg-page-body"><div class="tg-tag-head"><div><span class="tg-chip">#서울여행</span> <span class="tg-chip">#제주한달</span></div><strong>게시물 1,284개</strong></div><div class="tg-travel-grid"><c:forEach var="city" items="${['seoul','jeju','busan','seoul','gangneung','jeju']}"><img src="<c:url value='/assets/images/${city}.svg'/>" alt="태그 여행 사진"></c:forEach></div></section></c:when>
  <c:when test="${pageKey eq 'mission' or pageKey eq 'mission-active'}"><section class="tg-panel tg-page-body"><c:forEach var="mission" items="${['만원으로 하루 여행하기','대중교통만 이용하기','숨은 골목 사진 5장 남기기']}"><article class="tg-mission-card"><div class="tg-mission-icon"><i class="bi bi-flag"></i></div><div><h2 class="h6 mb-1">${mission}</h2><p class="text-secondary small mb-2">오늘의 여행 미션을 완료하고 기록을 남겨보세요.</p><div class="progress"><div class="progress-bar" style="width:${pageKey eq 'mission-active'?'60':'0'}%"></div></div></div><a class="btn btn-sm btn-primary" href="<c:url value='/mission-active'/>">${pageKey eq 'mission-active'?'진행 중':'도전하기'}</a></article></c:forEach></section></c:when>
  <c:when test="${pageKey eq 'profile'}"><section class="tg-panel tg-page-body"><div class="tg-profile-hero"><img class="tg-avatar" style="width:86px;height:86px" src="<c:url value='/assets/images/profile-ethan.svg'/>" alt="프로필"><div><h2>travel_ethan</h2><p class="text-secondary">적은 예산으로 오래 여행합니다.</p><div class="tg-profile-stats"><div><strong>24</strong><span>게시물</span></div><div><strong>1.2K</strong><span>팔로워</span></div><div><strong>318</strong><span>팔로잉</span></div></div></div></div><div class="tg-travel-grid"><c:forEach var="city" items="${['seoul','busan','jeju','gangneung','gyeongju','sokcho']}"><img src="<c:url value='/assets/images/${city}.svg'/>" alt="내 여행 기록"></c:forEach></div></section></c:when>
  <c:when test="${pageKey eq 'new-post'}"><section class="tg-panel tg-page-body"><form data-demo-form><div class="tg-upload mb-3"><div><i class="bi bi-images display-4"></i><p class="mt-2">사진이나 동영상을 여기에 끌어다 놓으세요.</p><input class="form-control" type="file" accept="image/*"></div></div><textarea class="form-control mb-3" rows="5" placeholder="여행 이야기를 작성하세요"></textarea><button class="btn btn-primary w-100">게시하기</button></form></section></c:when>
  <c:when test="${pageKey eq 'post-detail'}"><section class="tg-panel tg-detail-grid"><img src="<c:url value='/assets/images/seoul.svg'/>" alt="서울 여행"><div class="tg-page-body"><div class="tg-user-row"><img class="tg-avatar" src="<c:url value='/assets/images/profile-ethan.svg'/>" alt="ethan"><div><strong>travel_ethan</strong><small>서울 · 오늘</small></div></div><p>교통비 포함 2만원으로 즐긴 서울 하루 여행 코스입니다.</p><hr><h2 class="h6">댓글</h2><p><strong>travel_sora</strong> 다음 여행 때 참고할게요!</p><p><strong>budget_min</strong> 정말 알찬 코스네요.</p><form class="tg-compose" data-comment-form><input class="form-control" placeholder="댓글 달기"><button>게시</button></form></div></section></c:when>
  <c:when test="${pageKey eq 'feed-text'}"><article class="tg-panel tg-page-body tg-article"><h2>비 오는 제주에서 발견한 작은 마을</h2><p class="text-secondary">travel_sora · 2026년 7월 21일</p><p>계획에 없던 비가 내렸고, 우리는 해안도로 대신 작은 마을 안쪽으로 들어갔습니다. 오래된 돌담과 조용한 카페, 창문 너머의 귤밭이 하루의 속도를 천천히 낮춰주었습니다.\n\n여행은 계획대로 흘러가지 않을 때 더 오래 기억되는 것 같습니다.</p><p><a class="tg-hashtag" href="<c:url value='/tag'/>">#제주여행 #마을산책 #여행기록</a></p></article></c:when>
  <c:otherwise><div class="tg-auth-wrap"><section class="tg-panel tg-auth-card"><h2 class="tg-auth-title">travelgram</h2><c:choose><c:when test="${pageKey eq 'login'}"><form class="tg-stack" data-demo-form><input class="form-control" placeholder="아이디"><input class="form-control" type="password" placeholder="비밀번호"><button class="btn btn-primary">로그인</button><a class="btn btn-outline-secondary" href="<c:url value='/signup'/>">회원가입</a><a class="text-center small" href="<c:url value='/forgot-password'/>">비밀번호 찾기</a></form></c:when><c:when test="${pageKey eq 'signup'}"><form class="tg-stack" data-demo-form><input class="form-control" placeholder="이메일"><input class="form-control" placeholder="사용자 이름"><input class="form-control" type="password" placeholder="비밀번호"><input class="form-control" type="password" placeholder="비밀번호 확인"><button class="btn btn-primary">가입하기</button></form></c:when><c:otherwise><form class="tg-stack" data-demo-form><p class="text-secondary">가입한 이메일로 비밀번호 재설정 링크를 보내드립니다.</p><input class="form-control" type="email" placeholder="이메일"><button class="btn btn-primary">재설정 링크 보내기</button></form></c:otherwise></c:choose></section></div></c:otherwise>
</c:choose></main><jsp:include page="fragments/right-rail.jsp"/></div></div><script src="${appJs}"></script></body></html>
