USE ZAD;

-- 외래키 명칭 fk_현재테이블_참조테이블_참조컬럼명 --

-- 유저 --
CREATE TABLE IF NOT EXISTS USER(
	ID BIGINT primary KEY,
    USER_ID VARCHAR(50) unique,
    USER_PASSWORD VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30),
    NICKNAME VARCHAR(50)
);

-- 유저 코멘트 --
ALTER TABLE user COMMENT = '회원 정보 테이블';
ALTER TABLE user MODIFY COLUMN ID BIGINT COMMENT '유저 키';
ALTER TABLE user MODIFY COLUMN USER_ID VARCHAR(50) unique COMMENT '유저 아이디';
ALTER TABLE user MODIFY COLUMN USER_PASSWORD VARCHAR(30) NOT NULL COMMENT '유저 비밀번호';
ALTER TABLE user MODIFY COLUMN EMAIL VARCHAR(30) COMMENT '유저 이메일';
ALTER TABLE user MODIFY COLUMN NICKNAME VARCHAR(50) COMMENT '닉네임';

-- 게시글 --
CREATE TABLE IF NOT EXISTS POST(
	POST_ID BIGINT primary KEY,
    USER_ID BIGINT,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT NOT NULL,
    VIEW_COUNT INT,
    CREATE_AT DATETIME NOT NULL,
    IS_BLOCK bool 
);

ALTER TABLE POST COMMENT = '게시글 정보 테이블';
ALTER TABLE POST MODIFY COLUMN POST_ID BIGINT COMMENT '게시글 키';
ALTER TABLE POST MODIFY COLUMN USER_ID BIGINT COMMENT '유저 아이디';
ALTER TABLE POST MODIFY COLUMN TITLE VARCHAR(200) NOT NULL COMMENT '게시글 제목';
ALTER TABLE POST MODIFY COLUMN CONTENT TEXT NOT NULL COMMENT '게시글 내용';
ALTER TABLE POST MODIFY COLUMN VIEW_COUNT INT COMMENT '게시글 조회수';
ALTER TABLE POST MODIFY COLUMN NICKNAME VARCHAR(50) COMMENT '닉네임';

-- 게시글 좋아요 --
CREATE TABLE IF NOT EXISTS POST_LIKE(
	POST_LIKE_ID BIGINT primary KEY,
    POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATE_AT DATETIME NOT NULL
);

ALTER TABLE POST_LIKE 
ADD CONSTRAINT FK_POST_LIKE_POST_POST_ID FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID) ON DELETE CASCADE;

ALTER TABLE POST_LIKE 
ADD CONSTRAINT FK_POST_LIKE_USER_ID FOREIGN KEY (user_ID) REFERENCES user (id) ON DELETE CASCADE;

-- 실시간 톡 --
CREATE TABLE IF NOT EXISTS CHAT_MESSAGE(
	CHAT_ID BIGINT primary KEY,
    ID BIGINT NOT NULL,
    CONTENT VARCHAR(300),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);

ALTER TABLE CHAT_MESSAGE 
ADD CONSTRAINT FK_CHAT_MESSAGE_USER_ID FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE;

-- 톡 이미지 --
CREATE TABLE IF NOT EXISTS TALK_IMAGE(
	TALK_ID BIGINT primary KEY,
    CHAT_ID BIGINT NOT NULL,
    UPLOAD_ID BIGINT NOT NULL
);

ALTER TABLE TALK_IMAGE 
ADD CONSTRAINT FK_TALK_IMAGE_CHAT_MESSAGE_CHAT_ID FOREIGN KEY (CHAT_ID) REFERENCES CHAT_MESSAGE (CHAT_ID) ON DELETE CASCADE;

ALTER TABLE TALK_IMAGE 
ADD CONSTRAINT FK_TALK_IMAGE_IMAGE_UPLOAD_UPLOAD_ID FOREIGN KEY (UPLOAD_ID) REFERENCES IMAGE_UPLOAD (UPLOAD_ID) ON DELETE CASCADE;

-- 이미지 업로드 --
CREATE TABLE IF NOT EXISTS IMAGE_UPLOAD(
	UPLOAD_ID BIGINT primary KEY,
    ORIGIN_NAME VARCHAR(50) NOT NULL,
    UPLOAD_PATH VARCHAR(200) NOT NULL,
    IMAGE_ORDER SMALLINT NOT NULL
);

-- 게시글 업로드 연결 --
CREATE TABLE IF NOT EXISTS POST_UPLOAD(
	ID BIGINT primary KEY,
    POST_ID BIGINT NOT NULL,
    UPLOAD_ID BIGINT NOT NULL
);

ALTER TABLE POST_UPLOAD 
ADD CONSTRAINT FK_POST_UPLOAD_POST_POST_ID FOREIGN KEY (POST_ID) REFERENCES post (POST_ID) ON DELETE CASCADE;

ALTER TABLE POST_UPLOAD 
ADD CONSTRAINT FK_POST_UPLOAD_IMAGE_UPLOAD_UPLOAD_ID FOREIGN KEY (UPLOAD_ID) REFERENCES IMAGE_UPLOAD (UPLOAD_ID) ON DELETE CASCADE;

-- 댓글 --
CREATE TABLE IF NOT EXISTS COMMENT(
	COMMENT_ID BIGINT primary KEY,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    CONTENT VARCHAR(300),
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL
);

ALTER TABLE COMMENT 
ADD CONSTRAINT FK_COMMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES user (id) ON DELETE CASCADE;

ALTER TABLE COMMENT 
ADD CONSTRAINT FK_COMMENT_POST_POST_ID FOREIGN KEY (POST_ID) REFERENCES post (POST_ID) ON DELETE CASCADE;

-- 댓글 좋아요 --
CREATE TABLE IF NOT EXISTS COMMENT_LIKE(
	LIKE_ID BIGINT primary KEY,
    USER_ID BIGINT NOT NULL,
    COMMENT_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    CREATE_AT DATETIME NOT NULL
);

ALTER TABLE COMMENT_LIKE 
ADD CONSTRAINT FK_COMMENT_LIKE_USER_ID FOREIGN KEY (USER_ID) REFERENCES user (id) ON DELETE CASCADE;

ALTER TABLE COMMENT_LIKE 
ADD CONSTRAINT FK_COMMENT_LIKE_COMMENT_COMMENT_ID FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT (COMMENT_ID) ON DELETE CASCADE;

ALTER TABLE COMMENT_LIKE 
ADD CONSTRAINT FK_COMMENT_LIKE_POST_POST_ID FOREIGN KEY (POST_ID) REFERENCES post (POST_ID) ON DELETE CASCADE;

-- 미션 --
CREATE TABLE IF NOT EXISTS MISSION(
	MISSION_ID BIGINT primary KEY,
    MISSION_CONTENT TEXT NOT NULL,
    MISSION_CONDITION INT NOT NULL,
    MISSION_CATEGORY VARCHAR(50) NOT NULL,
    MISSION_CREATE_AT DATETIME NOT NULL
);

-- 미션 진행도 --
CREATE TABLE IF NOT EXISTS MISSION_PROGRESS(
	MISSION_PROGRESS_ID BIGINT PRIMARY KEY,
    ID BIGINT NOT NULL,
    MISSION_ID BIGINT NOT NULL,
    PROGRESS smallint unsigned,
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL,
    IS_DONE BOOL
);

ALTER TABLE MISSION_PROGRESS 
ADD CONSTRAINT FK_MISSION_PROGRESS_USER_ID FOREIGN KEY (id) REFERENCES user (ID) ON DELETE CASCADE;

ALTER TABLE MISSION_PROGRESS 
ADD CONSTRAINT FK_MISSION_PROGRESS_MISSION_MISSION_ID FOREIGN KEY (MISSION_ID) REFERENCES MISSION (MISSION_ID) ON DELETE CASCADE;

-- 팔로우 -- 
CREATE TABLE IF NOT EXISTS FOLLOWE(
	FOLLOWE_ID BIGINT primary KEY,
    FOLLOWER_ID BIGINT NOT NULL,
    FOLLOWERING_ID BIGINT NOT NULL,
    
    CONSTRAINT uk_follower_following UNIQUE (follower_id, FOLLOWERING_ID),
    
    -- 외래키 설정 (기존과 동일하게 유지 가능)
    FOREIGN KEY (follower_id) REFERENCES user(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWERING_ID) REFERENCES user(ID) ON DELETE CASCADE
);

-- 신고 --
CREATE TABLE IF NOT EXISTS REPORT(
	REPORT_ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    REPORT_STATUS ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED'),
    REPORT_CONTENT TEXT NOT NULL,
    REPORT_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME NOT NULL
);

ALTER TABLE REPORT 
ADD CONSTRAINT FK_REPORT_USER_ID FOREIGN KEY (USER_ID) REFERENCES user (id) ON DELETE CASCADE;

ALTER TABLE REPORT 
ADD CONSTRAINT FK_REPORT_POST_POST_ID FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE;