-- 1. 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS zad
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

-- 2. 사용자 계정 생성 (Docker 호스트 접속용 '%' 허용)
CREATE USER IF NOT EXISTS 'zzanmat'@'%' IDENTIFIED BY 'zzanmat';

-- 3. 권한 부여
GRANT ALL PRIVILEGES ON zad.* TO 'zzanmat'@'%';

-- 4. 권한 적용
FLUSH PRIVILEGES;

-- 5. zad 데이터베이스 선택
USE zad;

-- 6. 기존 테이블 삭제
DROP TABLE IF EXISTS MISSION_PROGRESS;
DROP TABLE IF EXISTS MISSION;
DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS FOLLOWE;
DROP TABLE IF EXISTS COMMENT_LIKE;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST_UPLOAD;
DROP TABLE IF EXISTS TALK_IMAGE;
DROP TABLE IF EXISTS CHAT_MESSAGE;
DROP TABLE IF EXISTS IMAGE_UPLOAD;
DROP TABLE IF EXISTS POST_LIKE;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS USER;

-- 유저 --
CREATE TABLE IF NOT EXISTS USER(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) UNIQUE,
    USER_PASSWORD VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(30),
    NICKNAME VARCHAR(50)
);

-- 유저 코멘트 --
ALTER TABLE USER COMMENT = '회원 정보 테이블';
ALTER TABLE USER MODIFY COLUMN ID BIGINT AUTO_INCREMENT COMMENT '유저 키';
ALTER TABLE USER MODIFY COLUMN USER_ID VARCHAR(50) UNIQUE COMMENT '유저 아이디';
ALTER TABLE USER MODIFY COLUMN USER_PASSWORD VARCHAR(100) NOT NULL COMMENT '유저 비밀번호';
ALTER TABLE USER MODIFY COLUMN EMAIL VARCHAR(30) COMMENT '유저 이메일';
ALTER TABLE USER MODIFY COLUMN NICKNAME VARCHAR(50) COMMENT '닉네임';

-- 게시글 --
CREATE TABLE IF NOT EXISTS POST(
	POST_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT TEXT NOT NULL,
    VIEW_COUNT INT,
    CREATE_AT DATETIME NOT NULL,
    IS_BLOCK BOOL
);

ALTER TABLE POST COMMENT = '게시글 정보 테이블';
ALTER TABLE POST MODIFY COLUMN POST_ID BIGINT AUTO_INCREMENT COMMENT '게시글 키';
ALTER TABLE POST MODIFY COLUMN USER_ID BIGINT COMMENT '유저 아이디';
ALTER TABLE POST MODIFY COLUMN TITLE VARCHAR(200) NOT NULL COMMENT '게시글 제목';
ALTER TABLE POST MODIFY COLUMN CONTENT TEXT NOT NULL COMMENT '게시글 내용';
ALTER TABLE POST MODIFY COLUMN VIEW_COUNT INT COMMENT '게시글 조회수';

-- 게시글 좋아요 --
CREATE TABLE IF NOT EXISTS POST_LIKE(
	POST_LIKE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATE_AT DATETIME NOT NULL
);

-- 실시간 톡 --
CREATE TABLE IF NOT EXISTS CHAT_MESSAGE(
	CHAT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID BIGINT NOT NULL,
    CONTENT VARCHAR(300),
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL
);

-- 이미지 업로드 --
CREATE TABLE IF NOT EXISTS IMAGE_UPLOAD(
	UPLOAD_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORIGIN_NAME VARCHAR(50) NOT NULL,
    UPLOAD_PATH VARCHAR(200) NOT NULL,
    IMAGE_ORDER SMALLINT NOT NULL
);

-- 톡 이미지 --
CREATE TABLE IF NOT EXISTS TALK_IMAGE(
	TALK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CHAT_ID BIGINT NOT NULL,
    UPLOAD_ID BIGINT NOT NULL
);

-- 게시글 업로드 연결 --
CREATE TABLE IF NOT EXISTS POST_UPLOAD(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    POST_ID BIGINT NOT NULL,
    UPLOAD_ID BIGINT NOT NULL
);

-- 댓글 --
CREATE TABLE IF NOT EXISTS COMMENT(
	COMMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    CONTENT VARCHAR(300),
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL
);

-- 댓글 좋아요 --
CREATE TABLE IF NOT EXISTS COMMENT_LIKE(
	LIKE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    COMMENT_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    CREATE_AT DATETIME NOT NULL
);

-- 미션 --
CREATE TABLE IF NOT EXISTS MISSION(
	MISSION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MISSION_CONTENT TEXT NOT NULL,
    MISSION_CONDITION INT NOT NULL,
    MISSION_CATEGORY VARCHAR(50) NOT NULL,
    CREATE_AT DATETIME NOT NULL
);

-- 미션 진행도 --
CREATE TABLE IF NOT EXISTS MISSION_PROGRESS(
	MISSION_PROGRESS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID BIGINT NOT NULL,
    MISSION_ID BIGINT NOT NULL,
    PROGRESS SMALLINT UNSIGNED,
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL,
    IS_DONE BOOL
);

-- 팔로우 --
CREATE TABLE IF NOT EXISTS FOLLOWE(
	FOLLOWE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FOLLOWER_ID BIGINT NOT NULL,
    FOLLOWERING_ID BIGINT NOT NULL,
    CONSTRAINT uk_follower_following UNIQUE (FOLLOWER_ID, FOLLOWERING_ID)
);

-- 신고 --
CREATE TABLE IF NOT EXISTS REPORT(
	REPORT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    REPORT_STATUS ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED'),
    REPORT_CONTENT TEXT NOT NULL,
    CREATE_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME NOT NULL
);
