-- ============================================================
-- 짠맛투어 최종 통합 초기화 스크립트
-- MYSQL 8.0 이상 기준
-- CREATE USER, ALTER USER, GRANT 문이 있으므로 MYSQL 관리자 계정으로 실행해야 합니다.
-- 주의: 실행 시 ZAD 데이터베이스의 기존 테이블과 데이터가 삭제됩니다.
-- ============================================================

CREATE DATABASE IF NOT EXISTS `ZAD`
    DEFAULT CHARACTER SET UTF8MB4
    DEFAULT COLLATE UTF8MB4_UNICODE_CI;

CREATE USER IF NOT EXISTS 'zzanmat'@'localhost' IDENTIFIED BY 'zzanmat';
ALTER USER 'zzanmat'@'localhost' IDENTIFIED BY 'zzanmat';
GRANT ALL PRIVILEGES ON `ZAD`.* TO 'zzanmat'@'localhost';

CREATE USER IF NOT EXISTS 'zzanmat'@'%' IDENTIFIED BY 'zzanmat';
ALTER USER 'zzanmat'@'%' IDENTIFIED BY 'zzanmat';
GRANT ALL PRIVILEGES ON `ZAD`.* TO 'zzanmat'@'%';

USE `ZAD`;
SET NAMES UTF8MB4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `USER_COUPON`;
DROP TABLE IF EXISTS `SHOP_ITEM`;
DROP TABLE IF EXISTS `POINT_HISTORY`;
DROP TABLE IF EXISTS `MISSION_HISTORY`;
DROP TABLE IF EXISTS `MISSION_PROGRESS`;
DROP TABLE IF EXISTS `MISSION_DELETE_ARCHIVE`;
DROP TABLE IF EXISTS `MISSION_UPDATE_HISTORY`;
DROP TABLE IF EXISTS `MISSION_CREATE_HISTORY`;
DROP TABLE IF EXISTS `MISSION_CREATE`;
DROP TABLE IF EXISTS `MISSION`;
DROP TABLE IF EXISTS `REPORT`;
DROP TABLE IF EXISTS `FOLLOWE`;
DROP TABLE IF EXISTS `COMMENT_LIKE`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `POST_UPLOAD`;
DROP TABLE IF EXISTS `TALK_IMAGE`;
DROP TABLE IF EXISTS `CHAT_MESSAGE`;
DROP TABLE IF EXISTS `IMAGE_UPLOAD`;
DROP TABLE IF EXISTS `POST_LIKE`;
DROP TABLE IF EXISTS `POST`;
DROP TABLE IF EXISTS `USER`;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 테이블 생성
-- ============================================================

CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원 PK',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '로그인 아이디 또는 소셜 식별자',
    `USER_PASSWORD` VARCHAR(255) NULL COMMENT '암호화 비밀번호',
    `EMAIL` VARCHAR(100) NULL COMMENT '이메일',
    `NICKNAME` VARCHAR(50) NOT NULL COMMENT '닉네임',
    `USER_NAME` VARCHAR(30) NULL COMMENT '회원 이름',
    `BIO` VARCHAR(255) NULL COMMENT '자기소개',
    `PROFILE` VARCHAR(500) NULL COMMENT '프로필 이미지 경로',
    `LOGIN_TYPE` ENUM('LOCAL', 'KAKAO', 'NAVER') NOT NULL DEFAULT 'LOCAL' COMMENT '로그인 유형',
    `ROLE` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER' COMMENT '회원 권한',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '회원 탈퇴 여부',
    `DELETED_AT` DATETIME NULL COMMENT '회원 탈퇴 일시',
    `LOGIN_SESSION_ID` VARCHAR(100) NULL COMMENT '현재 로그인 세션 식별자',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '가입 일시',
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (`ID`),
    CONSTRAINT `UK_USER_USER_ID` UNIQUE (`USER_ID`),
    CONSTRAINT `UK_USER_NICKNAME` UNIQUE (`NICKNAME`),
    INDEX `IDX_USER_EMAIL` (`EMAIL`),
    INDEX `IDX_USER_DELETED` (`IS_DELETED`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI COMMENT='회원 정보';

CREATE TABLE `POST` (
    `POST_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '게시글 PK',
    `USER_ID` BIGINT NOT NULL COMMENT '작성 회원 PK',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '게시글 제목',
    `CONTENT` TEXT NOT NULL COMMENT '게시글 내용',
    `PLACE` VARCHAR(100) NULL COMMENT '여행 장소',
    `VIEW_COUNT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '조회 수',
    `IS_BLOCK` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 또는 차단 여부',
    `IS_USER_WITHDRAWN` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '작성자 탈퇴 비노출 여부',
    `TRANSPORT_COST` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '교통비',
    `FOOD_COST` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '식비',
    `OTHER_COST` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '기타 비용',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성 일시',
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (`POST_ID`),
    CONSTRAINT `FK_POST_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON UPDATE CASCADE ON DELETE RESTRICT,
    INDEX `IDX_POST_USER` (`USER_ID`),
    INDEX `IDX_POST_VISIBLE_CREATED` (`IS_BLOCK`, `IS_USER_WITHDRAWN`, `CREATE_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI COMMENT='게시글';

CREATE TABLE `POST_LIKE` (
    `POST_LIKE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `POST_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`POST_LIKE_ID`),
    CONSTRAINT `UK_POST_LIKE_POST_USER` UNIQUE (`POST_ID`, `USER_ID`),
    CONSTRAINT `FK_POST_LIKE_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_POST_LIKE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    INDEX `IDX_POST_LIKE_USER` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `IMAGE_UPLOAD` (
    `UPLOAD_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `ORIGIN_NAME` VARCHAR(255) NOT NULL,
    `UPLOAD_PATH` VARCHAR(500) NOT NULL,
    `IMAGE_ORDER` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`UPLOAD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `POST_UPLOAD` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `POST_ID` BIGINT NOT NULL,
    `UPLOAD_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `UK_POST_UPLOAD_POST_UPLOAD` UNIQUE (`POST_ID`, `UPLOAD_ID`),
    CONSTRAINT `FK_POST_UPLOAD_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_POST_UPLOAD_UPLOAD` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `IMAGE_UPLOAD` (`UPLOAD_ID`) ON DELETE CASCADE,
    INDEX `IDX_POST_UPLOAD_UPLOAD` (`UPLOAD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `COMMENT` (
    `COMMENT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `POST_ID` BIGINT NOT NULL,
    `PARENT_COMMENT_ID` BIGINT NULL,
    `CONTENT` VARCHAR(300) NOT NULL,
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`COMMENT_ID`),
    CONSTRAINT `FK_COMMENT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_COMMENT_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_COMMENT_PARENT` FOREIGN KEY (`PARENT_COMMENT_ID`) REFERENCES `COMMENT` (`COMMENT_ID`) ON DELETE CASCADE,
    INDEX `IDX_COMMENT_USER` (`USER_ID`),
    INDEX `IDX_COMMENT_POST` (`POST_ID`),
    INDEX `IDX_COMMENT_PARENT` (`PARENT_COMMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `COMMENT_LIKE` (
    `LIKE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `COMMENT_ID` BIGINT NOT NULL,
    `POST_ID` BIGINT NOT NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`LIKE_ID`),
    CONSTRAINT `UK_COMMENT_LIKE_COMMENT_USER` UNIQUE (`COMMENT_ID`, `USER_ID`),
    CONSTRAINT `FK_COMMENT_LIKE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_COMMENT_LIKE_COMMENT` FOREIGN KEY (`COMMENT_ID`) REFERENCES `COMMENT` (`COMMENT_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_COMMENT_LIKE_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    INDEX `IDX_COMMENT_LIKE_USER` (`USER_ID`),
    INDEX `IDX_COMMENT_LIKE_POST` (`POST_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `FOLLOWE` (
    `FOLLOWE_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `FOLLOWER_ID` BIGINT NOT NULL,
    `FOLLOWERING_ID` BIGINT NOT NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`FOLLOWE_ID`),
    CONSTRAINT `UK_FOLLOWER_FOLLOWING` UNIQUE (`FOLLOWER_ID`, `FOLLOWERING_ID`),
    CONSTRAINT `FK_FOLLOWE_FOLLOWER` FOREIGN KEY (`FOLLOWER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_FOLLOWE_FOLLOWING` FOREIGN KEY (`FOLLOWERING_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    INDEX `IDX_FOLLOWE_FOLLOWING` (`FOLLOWERING_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `CHAT_MESSAGE` (
    `CHAT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `ID` BIGINT NOT NULL,
    `CONTENT` VARCHAR(300) NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`CHAT_ID`),
    CONSTRAINT `FK_CHAT_MESSAGE_USER` FOREIGN KEY (`ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    INDEX `IDX_CHAT_MESSAGE_USER` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `TALK_IMAGE` (
    `TALK_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CHAT_ID` BIGINT NOT NULL,
    `UPLOAD_ID` BIGINT NOT NULL,
    PRIMARY KEY (`TALK_ID`),
    CONSTRAINT `UK_TALK_IMAGE_CHAT_UPLOAD` UNIQUE (`CHAT_ID`, `UPLOAD_ID`),
    CONSTRAINT `FK_TALK_IMAGE_CHAT` FOREIGN KEY (`CHAT_ID`) REFERENCES `CHAT_MESSAGE` (`CHAT_ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_TALK_IMAGE_UPLOAD` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `IMAGE_UPLOAD` (`UPLOAD_ID`) ON DELETE CASCADE,
    INDEX `IDX_TALK_IMAGE_UPLOAD` (`UPLOAD_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `REPORT` (
    `REPORT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `POST_ID` BIGINT NOT NULL,
    `REPORT_STATUS` ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    `REPORT_CONTENT` TEXT NOT NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `COMPLETED_AT` DATETIME NULL,
    PRIMARY KEY (`REPORT_ID`),
    CONSTRAINT `FK_REPORT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_REPORT_POST` FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`) ON DELETE CASCADE,
    INDEX `IDX_REPORT_USER` (`USER_ID`),
    INDEX `IDX_REPORT_POST_STATUS` (`POST_ID`, `REPORT_STATUS`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `MISSION` (
    `MISSION_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '미션 고유 ID',
    `TITLE` VARCHAR(255) NOT NULL COMMENT '미션 제목',
    `DESCRIPTION` TEXT NULL COMMENT '미션 설명',
    `MISSION_TYPE` ENUM('POST', 'COMMENT', 'LIKE', 'CHAT') NOT NULL DEFAULT 'POST' COMMENT '미션 방식',
    `TRIGGER_EVENT` ENUM('CREATE_POST', 'CREATE_COMMENT', 'LIKE', 'OPEN_CHAT') NOT NULL DEFAULT 'CREATE_POST' COMMENT '트리거 이벤트',
    `TARGET_COUNT` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '목표 횟수',
    `REWARD_POINT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '보상 포인트',
    `AUTO_COMPLETE` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '자동 완료 여부',
    `PLACE_KEYWORD` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '게시글 장소 포함 키워드',
    `MAX_TOTAL_COST` BIGINT NOT NULL DEFAULT 0 COMMENT '총 경비 상한(원)',
    `START_AT` DATETIME(6) NULL COMMENT '수행 가능 시작 일시',
    `END_AT` DATETIME(6) NULL COMMENT '수행 가능 종료 일시',
    `CREATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UPDATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`MISSION_ID`),
    CONSTRAINT `CHK_MISSION_PERIOD` CHECK (`END_AT` IS NULL OR `START_AT` IS NULL OR `END_AT` > `START_AT`),
    INDEX `IDX_MISSION_TRIGGER` (`TRIGGER_EVENT`),
    INDEX `IDX_MISSION_PERIOD` (`START_AT`, `END_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI COMMENT='미션 정의 테이블';

CREATE TABLE `MISSION_PROGRESS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `MISSION_ID` BIGINT NOT NULL,
    `CURRENT_COUNT` INT UNSIGNED NOT NULL DEFAULT 0,
    `PROGRESS` INT UNSIGNED NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(50) NOT NULL DEFAULT 'IN_PROGRESS' COMMENT '진행 상태',
    `REWARD_RECEIVED` TINYINT(1) NOT NULL DEFAULT 0,
    `COMPLETED_AT` DATETIME(6) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UPDATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`ID`),
    CONSTRAINT `CHK_MISSION_PROGRESS_RATE` CHECK (`PROGRESS` BETWEEN 0 AND 100),
    CONSTRAINT `UK_MISSION_PROGRESS_USER_MISSION` UNIQUE (`USER_ID`, `MISSION_ID`),
    CONSTRAINT `FK_MISSION_PROGRESS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_MISSION_PROGRESS_MISSION` FOREIGN KEY (`MISSION_ID`) REFERENCES `MISSION` (`MISSION_ID`) ON DELETE CASCADE,
    INDEX `IDX_MISSION_PROGRESS_USER_STATUS` (`USER_ID`, `STATUS`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `POINT_HISTORY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `MISSION_ID` BIGINT NULL,
    `POINT` INT NOT NULL,
    `REASON` ENUM('MISSION', 'EVENT', 'ADMIN', 'PURCHASE') NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_POINT_HISTORY_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE RESTRICT,
    CONSTRAINT `FK_POINT_HISTORY_MISSION` FOREIGN KEY (`MISSION_ID`) REFERENCES `MISSION` (`MISSION_ID`) ON DELETE SET NULL,
    INDEX `IDX_POINT_HISTORY_USER` (`USER_ID`),
    INDEX `IDX_POINT_HISTORY_MISSION` (`MISSION_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `SHOP_ITEM` (
    `ITEM_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `CATEGORY` ENUM('GIFT_CARD', 'TRAVEL', 'FLIGHT', 'TRAIN') NOT NULL,
    `COST_POINT` INT NOT NULL,
    `STOCK` INT NULL COMMENT 'NULL이면 무제한',
    `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ITEM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE `USER_COUPON` (
    `COUPON_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ITEM_ID` BIGINT NOT NULL,
    `COUPON_CODE` VARCHAR(40) NOT NULL,
    `COST_POINT` INT NOT NULL,
    `STATUS` ENUM('AVAILABLE', 'USED', 'EXPIRED') NOT NULL DEFAULT 'AVAILABLE',
    `PURCHASED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`COUPON_ID`),
    CONSTRAINT `UK_USER_COUPON_CODE` UNIQUE (`COUPON_CODE`),
    CONSTRAINT `FK_USER_COUPON_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_USER_COUPON_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `SHOP_ITEM` (`ITEM_ID`) ON DELETE RESTRICT,
    INDEX `IDX_USER_COUPON_USER` (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;
