-- 테이블 PK값 자동 증가 설정 -- 
ALTER TABLE USER MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE POST MODIFY COLUMN POST_ID BIGINT AUTO_INCREMENT;
ALTER TABLE POST_LIKE MODIFY COLUMN POST_LIKE_ID BIGINT AUTO_INCREMENT;
ALTER TABLE CHAT_MESSAGE MODIFY COLUMN CHAT_ID BIGINT AUTO_INCREMENT;
ALTER TABLE TALK_IMAGE MODIFY COLUMN TALK_ID BIGINT AUTO_INCREMENT;
ALTER TABLE IMAGE_UPLOAD MODIFY COLUMN UPLOAD_ID BIGINT AUTO_INCREMENT;
ALTER TABLE POST_UPLOAD MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE COMMENT MODIFY COLUMN COMMENT_ID BIGINT AUTO_INCREMENT;
ALTER TABLE COMMENT_LIKE MODIFY COLUMN LIKE_ID BIGINT AUTO_INCREMENT;
ALTER TABLE MISSION MODIFY COLUMN MISSION_ID BIGINT AUTO_INCREMENT;
ALTER TABLE MISSION_PROGRESS MODIFY COLUMN MISSION_PROGRESS_ID BIGINT AUTO_INCREMENT;
ALTER TABLE FOLLOWE MODIFY COLUMN FOLLOWE_ID BIGINT AUTO_INCREMENT;
ALTER TABLE REPORT MODIFY COLUMN REPORT_ID BIGINT AUTO_INCREMENT;

-- 날짜 명칭 수정 --
ALTER TABLE REPORT RENAME COLUMN REPORT_AT TO CREATE_AT;
ALTER TABLE MISSION RENAME COLUMN MISSION_CREATE_AT TO CREATE_AT;
ALTER TABLE CHAT_MESSAGE RENAME COLUMN CREATED_AT TO CREATE_AT;
ALTER TABLE CHAT_MESSAGE RENAME COLUMN UPDATED_AT TO UPDATE_AT;

