ALTER TABLE `POST`
	ADD COLUMN `TRANSPORT_COST` BIGINT NOT NULL DEFAULT 0
		COMMENT '교통비',
	ADD COLUMN `FOOD_COST` BIGINT NOT NULL DEFAULT 0
		COMMENT '식비',
	ADD COLUMN `OTHER_COST` BIGINT NOT NULL DEFAULT 0
		COMMENT '입장료 및 기타 비용';
        
DESCRIBE `POST`;

