USE zad;

SELECT
	COMMENT_ID,
    USER_ID,
    COUNT(*) AS LIKE_COUNT
FROM COMMENT_LIKE
GROUP BY COMMENT_ID, USER_ID
HAVING COUNT(*) > 1;

ALTER TABLE COMMENT_LIKE
	ADD CONSTRAINT UK_COMMENT_LIKE_COMMENT_USER
		UNIQUE (COMMENT_ID, USER_ID);